/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RRouteImport } from './routes/r'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as UnauthenticatedIndexRouteImport } from './routes/_unauthenticated/index'
import { Route as RRoomNameRouteImport } from './routes/r/$roomName'

const RRoute = RRouteImport.update({
  id: '/r',
  path: '/r',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedIndexRoute = UnauthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const RRoomNameRoute = RRoomNameRouteImport.update({
  id: '/$roomName',
  path: '/$roomName',
  getParentRoute: () => RRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof UnauthenticatedIndexRoute
  '/r': typeof RRouteWithChildren
  '/r/$roomName': typeof RRoomNameRoute
}
export interface FileRoutesByTo {
  '/r': typeof RRouteWithChildren
  '/r/$roomName': typeof RRoomNameRoute
  '/': typeof UnauthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/r': typeof RRouteWithChildren
  '/r/$roomName': typeof RRoomNameRoute
  '/_unauthenticated/': typeof UnauthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/r' | '/r/$roomName'
  fileRoutesByTo: FileRoutesByTo
  to: '/r' | '/r/$roomName' | '/'
  id:
    | '__root__'
    | '/_unauthenticated'
    | '/r'
    | '/r/$roomName'
    | '/_unauthenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  RRoute: typeof RRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/r': {
      id: '/r'
      path: '/r'
      fullPath: '/r'
      preLoaderRoute: typeof RRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/': {
      id: '/_unauthenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedIndexRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/r/$roomName': {
      id: '/r/$roomName'
      path: '/$roomName'
      fullPath: '/r/$roomName'
      preLoaderRoute: typeof RRoomNameRouteImport
      parentRoute: typeof RRoute
    }
  }
}

interface UnauthenticatedRouteChildren {
  UnauthenticatedIndexRoute: typeof UnauthenticatedIndexRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedIndexRoute: UnauthenticatedIndexRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

interface RRouteChildren {
  RRoomNameRoute: typeof RRoomNameRoute
}

const RRouteChildren: RRouteChildren = {
  RRoomNameRoute: RRoomNameRoute,
}

const RRouteWithChildren = RRoute._addFileChildren(RRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  RRoute: RRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
